name = "dbapi"
main = "src/index.ts"
compatibility_date = "2024-05-22"
workers_dev = true
# node_compat = true

routes = [
	{ pattern = "api.dry.nl.eu.org", custom_domain = true }
]

[placement]
mode = "smart"

